name: patapata_builder
version: 1.0.0
description: todo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  patapata_core: ^1.2.0

  meta: ^1.15.0
  analyzer: '>=5.13.0'
  build: ^2.0.0
  build_config: '>=1.1.1'
  source_gen: '>=1.3.2'

dev_dependencies:
  build_runner: ^2.4.14
  dart_flutter_team_lints: ^1.0.0
