name: patapata_firebase_analytics
description: This package is a plugin for Patapata that adds support for Firebase Analytics to your Patapata app.
version: 1.0.0
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/packages/patapata_firebase_analytics

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.0.0

  patapata_firebase_core: ^1.0.0

  firebase_analytics: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
