name: patapata_firebase_auth
description: This package is a plugin for Patapata that adds support for Firebase Authentication to your Patapata app.
version: 1.0.1
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_auth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.0.1

  firebase_auth: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
