name: patapata_riverpod
description: This package is a plugin for Patapata that adds support for Riverpod to your Patapata app.
version: 1.0.2
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_riverpod

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.6
  patapata_core: ^1.0.2
  riverpod_annotation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  riverpod_generator: ^2.3.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4

flutter:
